from .dashboard_view import *
from .tree_data_add import *
from .addTree_view import *
from .treeData_view import *
from .addLog_view import *
from .treeSpace_login_view import *
from .home_view import *
from .joyces_kitchen_view import *
from .environmental_view import *
from .store_view import *
from .irrigation_core import *
from .views_pos import *
from .upick_view import *
from .upick_dashboard_view import *