# Generated by Django 4.1.7 on 2023-03-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='individualTrees_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treeID', models.CharField(max_length=10)),
                ('rootStock', models.CharField(max_length=10)),
                ('zionType', models.CharField(max_length=10)),
                ('datePlanted', models.DateField()),
            ],
        ),
    ]
