# Generated by Django 4.1.7 on 2023-04-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='areaTree_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treeID', models.CharField(max_length=10)),
                ('rootStock', models.CharField(max_length=10)),
                ('zionType', models.CharField(max_length=10)),
                ('datePlanted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='locationTree_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treeID', models.CharField(max_length=10)),
                ('rootStock', models.CharField(max_length=10)),
                ('zionType', models.CharField(max_length=10)),
                ('datePlanted', models.DateField()),
            ],
        ),
    ]
