# Generated by Django 4.1.7 on 2023-04-04 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0002_areatree_model_locationtree_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='logCategory_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='areatree_model',
            old_name='treeID',
            new_name='areaID',
        ),
        migrations.RenameField(
            model_name='areatree_model',
            old_name='datePlanted',
            new_name='dateEst',
        ),
        migrations.RenameField(
            model_name='locationtree_model',
            old_name='datePlanted',
            new_name='dateEst',
        ),
        migrations.RenameField(
            model_name='locationtree_model',
            old_name='treeID',
            new_name='locationID',
        ),
        migrations.RemoveField(
            model_name='areatree_model',
            name='rootStock',
        ),
        migrations.RemoveField(
            model_name='areatree_model',
            name='zionType',
        ),
        migrations.RemoveField(
            model_name='locationtree_model',
            name='rootStock',
        ),
        migrations.RemoveField(
            model_name='locationtree_model',
            name='zionType',
        ),
        migrations.AddField(
            model_name='areatree_model',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationtree_model',
            name='address',
            field=models.CharField(default='-', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationtree_model',
            name='city',
            field=models.CharField(default='-', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationtree_model',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationtree_model',
            name='state',
            field=models.CharField(default='-', max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='treeLogs_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('note', models.CharField(max_length=10000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allTrees.logcategory_model')),
                ('treeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allTrees.individualtrees_model')),
            ],
        ),
    ]
