# Generated by Django 4.1.7 on 2023-04-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0003_logcategory_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatree_model',
            name='lengthByTree',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='areatree_model',
            name='widthByTree',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
