# Generated by Django 4.1.7 on 2023-04-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0004_areatree_model_lengthbytree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtrees_model',
            name='treeID',
            field=models.CharField(max_length=20),
        ),
    ]
