# Generated by Django 4.1.7 on 2023-11-17 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0006_areatree_model_locationid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tree_qr',
            fields=[
                ('treeID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='allTrees.individualtrees_model')),
                ('url', models.CharField(max_length=300)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
    ]
