# Generated by Django 3.2.7 on 2023-12-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0007_tree_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('ingredients', models.JSONField()),
                ('equipment', models.JSONField()),
                ('serving_size', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(max_length=20)),
                ('meal_type', models.CharField(choices=[('dessert', 'Dessert'), ('dinner-main', 'Dinner - Main'), ('dinner-side', 'Dinner - Side'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('brunch', 'Brunch'), ('quick snack', 'Quick Snack')], max_length=60)),
                ('directions', models.TextField(max_length=20000)),
                ('special_notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('healthy_choice', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=7)),
            ],
        ),
    ]
