# Generated by Django 3.2.7 on 2023-12-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0008_recipemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='healthy_choice',
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='cuisine',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='freezer_friendly',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='time',
            field=models.CharField(max_length=70),
        ),
    ]
