# Generated by Django 3.2.7 on 2023-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0009_auto_20231217_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='time',
            field=models.JSONField(),
        ),
    ]
