# Generated by Django 3.2.7 on 2023-12-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0013_auto_20231220_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstore_products',
            name='limit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='ribbon',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
