# Generated by Django 3.2.7 on 2023-12-20 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allTrees', '0016_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatree_model',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allTrees.mainstore_products'),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationtree_model',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
