# Generated by Django 3.2.7 on 2023-12-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0017_auto_20231220_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstore_products',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/'),
        ),
    ]
