# Generated by Django 3.2.7 on 2023-12-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0018_alter_mainstore_products_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipe_images/'),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipe_images/'),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipe_images/'),
        ),
        migrations.AddField(
            model_name='recipemodel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipe_images/'),
        ),
    ]
