# Generated by Django 4.2.9 on 2025-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0019_auto_20231221_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='valve_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('valveIP', models.CharField(max_length=17)),
            ],
        ),
    ]
