# Generated by Django 4.2.9 on 2025-06-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0020_valve_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='valve_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.CharField(max_length=100)),
                ('valve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allTrees.valve_registration')),
            ],
        ),
    ]
