# Generated by Django 3.2.7 on 2025-06-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0019_auto_20240105_2033'),
        ('allTrees', '0021_valve_schedule'),
    ]

    operations = [
    ]
