# Generated by Django 4.2.9 on 2025-06-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0022_merge_0019_auto_20240105_2033_0021_valve_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtrees_model',
            name='locationID',
        ),
        migrations.AddField(
            model_name='individualtrees_model',
            name='status',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('missing', 'Missing'), ('dead', 'Dead')], default='healthy', max_length=10),
        ),
    ]
