# Generated by Django 4.2.9 on 2025-06-13 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0023_remove_individualtrees_model_locationid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve_registration',
            name='areaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allTrees.areatree_model'),
        ),
        migrations.AddField(
            model_name='valve_registration',
            name='sub_area',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
