# Generated by Django 3.2.7 on 2025-06-15 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0024_valve_registration_areaid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treelogs_model',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='treelogs_model',
            name='date',
        ),
        migrations.RemoveField(
            model_name='treelogs_model',
            name='time',
        ),
        migrations.AddField(
            model_name='treelogs_model',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualtrees_model',
            name='rootStock',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='individualtrees_model',
            name='zionType',
            field=models.CharField(default='none', max_length=10),
        ),
        migrations.AddIndex(
            model_name='treelogs_model',
            index=models.Index(fields=['treeID'], name='allTrees_tr_treeID__b38387_idx'),
        ),
        migrations.AddIndex(
            model_name='treelogs_model',
            index=models.Index(fields=['timestamp'], name='allTrees_tr_timesta_f884eb_idx'),
        ),
    ]
