# Generated by Django 3.2.7 on 2025-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0025_auto_20250615_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve_registration',
            name='manual_override',
            field=models.BooleanField(default=False),
        ),
    ]
