# Generated by Django 3.2.7 on 2026-03-19 05:30

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allTrees', '0026_valve_registration_manual_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('voided', 'Voided'), ('refunded', 'Refunded')], default='open', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('tap_to_pay', 'Tap to Pay'), ('manual_card', 'Manual Card'), ('other', 'Other')], max_length=20, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_receipt_url', models.URLField(blank=True, null=True)),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pos_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='allow_custom_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='is_active_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='is_active_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='pos_display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='sku',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='unit_type',
            field=models.CharField(choices=[('each', 'Each'), ('weight', 'Weight')], default='each', max_length=20),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='shipping_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_pos_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_pos_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POSSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('sku_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sold_by_weight', models.BooleanField(default=False)),
                ('weight_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale_items', to='allTrees.mainstore_products')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='allTrees.possale')),
            ],
        ),
        migrations.AddField(
            model_name='possale',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='allTrees.possession'),
        ),
        migrations.CreateModel(
            name='POSPaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='allTrees.possale')),
            ],
        ),
    ]
