# Generated by Django 3.2.7 on 2026-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0027_auto_20260319_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='possale',
            name='stripe_payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='possale',
            name='stripe_terminal_location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='possale',
            name='stripe_terminal_reader_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
