# Generated by Django 3.2.7 on 2026-04-24 02:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0028_auto_20260319_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainstore_products',
            options={'ordering': ['store_display_order', 'product_name'], 'verbose_name': 'Store Product', 'verbose_name_plural': 'Store Products'},
        ),
        migrations.RemoveField(
            model_name='mainstore_products',
            name='limit',
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='allow_backorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='alt_text',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='fulfillment_type',
            field=models.CharField(choices=[('pickup_only', 'Pickup Only'), ('shipping_only', 'Shipping Only'), ('pickup_or_shipping', 'Pickup or Shipping'), ('local_delivery', 'Local Delivery')], default='pickup_only', max_length=30),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='harvest_date',
            field=models.DateField(blank=True, help_text='Useful for fresh-picked produce.', null=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='is_seasonal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='limit_per_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='product_type',
            field=models.CharField(choices=[('produce', 'Produce'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('herb_spice', 'Herbs / Spices'), ('plant', 'Plant'), ('preserved_good', 'Preserved Good'), ('merch', 'Merchandise'), ('digital', 'Digital'), ('other', 'Other')], default='produce', max_length=30),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='season_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='season_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='store_display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='taxable',
            field=models.BooleanField(default=True, help_text='Some food/produce may be taxed differently depending on rules.'),
        ),
        migrations.AddField(
            model_name='mainstore_products',
            name='unit_label',
            field=models.CharField(blank=True, help_text="Optional display label like 'per quart', 'per lb', 'per bunch'", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='allow_custom_price',
            field=models.BooleanField(default=False, help_text='Useful for POS/manual farm stand pricing.'),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='inventory_status',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('seasonal_unavailable', 'Seasonal / Unavailable')], default='in_stock', max_length=75),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='inventory_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Can support counts or weight-based inventory, like 25 quarts or 40.5 lbs.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='is_active_offline',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='limit_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='pre_order_message',
            field=models.CharField(blank=True, help_text='Example: Available for pickup Saturday morning.', max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='product_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='ribbon',
            field=models.CharField(blank=True, help_text='Example: Fresh Picked, New, Best Seller, Limited Batch', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='sale_percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='shipping_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Weight in pounds for shipping calculations.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='sku',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mainstore_products',
            name='unit_type',
            field=models.CharField(choices=[('each', 'Each'), ('lb', 'Pound'), ('oz', 'Ounce'), ('quart', 'Quart'), ('pint', 'Pint'), ('half_pint', 'Half Pint'), ('bushel', 'Bushel'), ('bunch', 'Bunch'), ('bag', 'Bag'), ('box', 'Box'), ('jar', 'Jar'), ('bundle', 'Bundle'), ('custom', 'Custom')], default='each', help_text='How this item is sold, like each, pound, quart, bunch, jar, etc.', max_length=30),
        ),
    ]
