# Generated by Django 3.2.7 on 2026-04-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0029_auto_20260423_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainStore_product_variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(blank=True, help_text='Example: Small, Large, Quart, Pint, 2XL, Red XL', max_length=100, null=True)),
                ('size', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'XL'), ('2xl', '2XL'), ('3xl', '3XL'), ('4xl', '4XL'), ('youth_s', 'Youth Small'), ('youth_m', 'Youth Medium'), ('youth_l', 'Youth Large'), ('custom', 'Custom')], max_length=30, null=True)),
                ('sku', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the parent product price.', max_digits=10, null=True)),
                ('sale_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional sale price for this specific variant.', max_digits=10, null=True)),
                ('track_inventory', models.BooleanField(default=True)),
                ('inventory_total', models.DecimalField(blank=True, decimal_places=2, help_text='Inventory for this specific size/variant.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_active_online', models.BooleanField(default=True)),
                ('is_active_offline', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='allTrees.mainstore_products')),
            ],
            options={
                'verbose_name': 'Store Product Variant',
                'verbose_name_plural': 'Store Product Variants',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
