# Generated by Django 3.2.7 on 2026-04-24 02:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0030_mainstore_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_items',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart_items',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='allTrees.mainstore_product_variants'),
        ),
    ]
