# Generated by Django 3.2.7 on 2026-04-24 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allTrees', '0031_auto_20260423_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(default='Strawberries', max_length=100)),
                ('title', models.CharField(default='U-Pick Strawberries', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('default_slot_capacity', models.PositiveIntegerField(default=10)),
                ('default_slot_minutes', models.PositiveIntegerField(default=60)),
                ('grace_period_minutes', models.PositiveIntegerField(default=15)),
                ('weather_note', models.CharField(blank=True, max_length=255, null=True)),
                ('field_note', models.CharField(blank=True, max_length=255, null=True)),
                ('rules_text', models.TextField(blank=True, default='Your reservation time is your scheduled arrival/check-in time. Please arrive within 15 minutes of your scheduled time. Reservations not checked in within 15 minutes may be released for walk-ins. Picking time is expected to last up to 60–90 minutes depending on field conditions and crop availability. All guests must check in before entering the field. Children must stay with an adult. No pets in the picking field. Please only pick what you plan to purchase.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'U-Pick Event',
                'verbose_name_plural': 'U-Pick Events',
                'ordering': ['date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UPickTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_walk_in_available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='allTrees.upickevent')),
            ],
            options={
                'verbose_name': 'U-Pick Time Slot',
                'verbose_name_plural': 'U-Pick Time Slots',
                'ordering': ['event__date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='UPickReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('released', 'Released to Walk-ins')], default='confirmed', max_length=30)),
                ('agreed_to_rules', models.BooleanField(default=False)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('internal_note', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='allTrees.upicktimeslot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'U-Pick Reservation',
                'verbose_name_plural': 'U-Pick Reservations',
                'ordering': ['time_slot__event__date', 'time_slot__start_time', 'last_name'],
            },
        ),
    ]
