# Generated by Django 3.2.7 on 2026-04-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0032_upickevent_upickreservation_upicktimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
