# Generated by Django 3.2.7 on 2026-04-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0034_storeorder_storeorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='billing_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='billing_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='billing_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='billing_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='billing_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='billing_state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
