# Generated by Django 3.2.7 on 2026-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0035_auto_20260429_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmNewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('source', models.CharField(default='our_story_page', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Farm Newsletter Subscriber',
                'verbose_name_plural': 'Farm Newsletter Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
