# Generated by Django 3.2.7 on 2026-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0036_farmnewslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('announcement_type', models.CharField(choices=[('general', 'General Update'), ('harvest', 'Harvest Update'), ('upick', 'U-Pick Update'), ('store', 'Store Update'), ('event', 'Event'), ('weather', 'Weather Notice'), ('closed', 'Closure Notice'), ('garden', 'Garden Update'), ('other', 'Other')], default='general', max_length=30)),
                ('summary', models.CharField(help_text='Short preview text shown on the announcements page.', max_length=280)),
                ('body', models.TextField(help_text='Full announcement/news post content.')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='announcement_images/')),
                ('image_alt_text', models.CharField(blank=True, max_length=180, null=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements appear before regular posts.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('publish_date', models.DateTimeField(help_text='Date/time this announcement should appear as published.')),
                ('meta_title', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farm Announcement',
                'verbose_name_plural': 'Farm Announcements',
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
    ]
