# Generated by Django 3.2.7 on 2026-06-16 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0037_farmannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='upick_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='allTrees.upickreservation'),
        ),
    ]
