# Generated by Django 3.2.7 on 2026-06-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0038_possale_upick_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmnewslettersubscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='farmnewslettersubscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
