# Generated by Django 3.2.7 on 2026-06-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0039_auto_20260617_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='receipt_email_last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='possale',
            name='receipt_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
