# Generated by Django 3.2.7 on 2026-06-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0040_auto_20260619_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatree_model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areatree_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='area_images/'),
        ),
        migrations.AddField(
            model_name='individualtrees_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tree_images/'),
        ),
        migrations.AddField(
            model_name='individualtrees_model',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='individualtrees_model',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationtree_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='location_images/'),
        ),
        migrations.AlterField(
            model_name='locationtree_model',
            name='locationID',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='areatree_model',
            constraint=models.UniqueConstraint(fields=('locationID', 'areaID'), name='unique_area_per_location'),
        ),
        migrations.AddConstraint(
            model_name='individualtrees_model',
            constraint=models.UniqueConstraint(fields=('areaID', 'treeID'), name='unique_tree_per_area'),
        ),
    ]
