# Generated by Django 3.2.7 on 2026-06-23 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0041_auto_20260619_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPickWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_type', models.CharField(choices=[('any', 'Any available day/time'), ('day', 'Preferred day')], default='any', max_length=20)),
                ('preferred_date', models.DateField(blank=True, help_text='Only used if customer selected preferred day.', null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('people_count', models.PositiveIntegerField(default=1)),
                ('estimated_quarts', models.PositiveIntegerField(blank=True, help_text='Estimated number of quarts the customer would like.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('converted', 'Converted to Reservation'), ('removed', 'Removed')], default='waiting', max_length=20)),
                ('removed_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_waitlist_entries', to='allTrees.upickreservation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='allTrees.upickevent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
