# Generated by Django 3.2.7 on 2026-06-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0042_upickwaitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='upickreservation',
            name='estimated_quarts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
