# Generated by Django 3.2.7 on 2026-06-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allTrees', '0043_upickreservation_estimated_quarts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upickwaitlistentry',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='allTrees.upickevent'),
        ),
    ]
